spring:
  datasource:
    url: jdbc:h2:mem:petProjectDB/?username=sa&password=sa
    driverClassName: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8



  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    user: sql11473491
    password: PchsC7yWZh
    locations: classpath:/db/changelog/