#spring:
#  datasource:
#    url: jdbc:h2:mem:petProjectDB/?username=sa&password=sa
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: rg.hibernate.dialect.H2Dialect
#    show-sql: true
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-admin-password: sa
#        web-allow-others: true

#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.xml
spring:
  thymeleaf:
    mode: html
  jpa:
    open-in-view: false
logging:
  level:
    liquibase: INFO