spring:
  datasource:
    url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11473491
    driverClassName: com.mysql.jdbc.Driver
    password: PchsC7yWZh
    username: sql11473491

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    user: sql11473491
    password: PchsC7yWZh
    locations: classpath:/db/changelog/

jwt:
  secret: jWtSecreTk_e_y
  expiration: 30