spring:
  datasource:
    url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11473491;username=sql11473491;passwordPchsC7yWZh
    driverClassName: com.mysql.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialec
    show-sql: true
  flyway:
    user: sql11473491
    password: PchsC7yWZh
    locations: classpath:/db/changelog/


