spring:
  datasource:
    url: jdbc:postgresql://ec2-54-217-15-9.eu-west-1.compute.amazonaws.com:5432/d13dajj1p2915
    driverClassName: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    user: fureeaundkskmo
    password: 9be7e5c5b5f9c10ce19c57fa9b42e0a7a2907e27796f93795072062664217b53
    locations: classpath:/db/changelog/


